WebApplication1/WebApplication1/Controllers/UyelerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class UyelerController : Controller
    {
        // GET: Uyeler
    
        public ActionResult UyeAnaSinif()
        {
            return View();
        }
        public ActionResult Anketlerim()
        {
            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <style type="text/css">
            /*Madde imlerini kaldırıp tüm başlıkları alt alta sıralayalım.*/
            #menum ul {
                list-style: none;
                margin: 0;
                padding: 0;
            }
            /*Ana menü başlıklarının alt alta değil de soldan sağa doğru sıralanması için float:left; özelliğine kullanalım. Çünkü yatay menü yapıyoruz.*/
            #menum li {
                float: left;
                position: relative;
                width: 150px;
            }
                /*
        Şimdi alt menu olarak açılacak alt menümüzün ayarlamasını yapıyoruz.
        Alt menü olarak açılacak menümüzün pozisyonunu : Satır yüksekliği (line-height) + kenar boşluğu (padding) + kenar çizgi kalınlıkları

        Satır yüksekliğini sonradan 16 px vereceğiz. Alt ve üst kenar boşluklarına 2 px verelim, kenar çizgileri de 1px olsun (alt ve üst hesaba dahil olacak),
        Toplam 16+(2x2)+(2x1)=22 px olacaktır.

        Alt açılan menünün üst çizgisi ile üst menümüzün alt çizgisi üst üste geleceği için alt menümüzün açılması gereken pozisyonu, yukarıdan 22-1=21 px olarak ayarlamamız daha doğru olacaktır. Yine sayfamız ilk yüklendiğinde alt menünün gözükmemesi için “display:none;” yapılmalıdır.
        */
                #menum li ul {
                    display: none; /*Alt menüleri görünmez yapar*/
                    left: 0; /*Soldan boşlukları temizler*/
                    position: absolute; /*Alt menünün poziyonunu üst menüye göre göreceli olarak ayarlar*/
                    top: 21px; /*üstten 21px boşluk bırakır*/
                }
            /*Menümüze biraz görsellik katalım*/
            #menum ul li a {
                background: #c2d378;
                border: none;
                border-bottom-color: none;
                color: #170101;
                display:block;
                font: bold 12px Arial, Helvetica, sans-serif;
                margin: 0;
                padding: 3px 5px;
                text-decoration: none;
                line-height: 16px;
            }
                /*Menü üzerine geldiğimizde yazıların kırmızı olması ve zeminin renginin beyaz kalması için*/
                #menum ul li a:hover {
                    background: #c2d378;
                    color: #cfffc4;
                }
            /*Üzerine geldiğimizde Alt menülerin gözükmesi için ise*/
            #menum li:hover ul {
                display: block;
            }
    </style>



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" >
            
                <h2 style="font-size:15px">
                    <a><img src="~/images/anketeam.jpg" width="300" height="60" alt="Örnek Resim"></a>
    

                </h2>
            
            
            <div class="navbar-header">
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>


            </div>

            


            <div class="navbar-collapse collapse">



                <div id="menum">
                    
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Anasayfa", "Index", "Home")</li>
                        <li>@Html.ActionLink("Kullanım Şekli", "KullanimSekli", "Home")</li>


                        <li>
                            <a href="#">Örnekler</a>
                            <ul>
                                <li>@Html.ActionLink("Anket Örnekleri", "Ornekler", "Home")</li>
                                <li>@Html.ActionLink("Anket Şablonları", "AnketSablonlari", "Home")</li>
                                <li>@Html.ActionLink("Anket Türleri", "AnketTurleri", "Home")</li>
                                <li>@Html.ActionLink("Anket İpucları", "AnketIpuclari", "Home")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#">Anket Hizmetleri</a>
                            <ul>
                                <li>@Html.ActionLink("Çok Kullanıcılı Bir Hesap Satın Alın", "AnketHizmetleri", "Home")</li>
                                <li>@Html.ActionLink("Anket Kıstasları", "AnketKistaslari", "Home")</li>
                                
                            </ul>
                        </li>


                        <li>@Html.ActionLink("Planlar ve Fiyatlandırma", "PlanlarveFiyatlandirma", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>

        
    </div>
        <BR>   </BR> 
        <BR>   </BR> 

   
   
        <ul class="navbar  navbar-right" >
            <h1 style="font-size:20px"><a>Bizi takip <br /> edin</a> </h1>
            <li><a href="http://www.facebook.com.tr/anketeam"><img src="~/images/face.png" width="30" height="30" alt="Facebook">  </a></li>
            <li> <a href="https://twitter.com/nuranozdemir61"><img src="~/images/twitter.png" width="30" height="30" alt="Twitter">  </a></li>
            <li> <a href="https://www.linkedin.com"><img src="~/images/lin.png" width="30" height="30" alt="LinkedIn">  </a></li>
            <li> <a href="https://plus.google.com"><img src="~/images/google.jpg" width="30" height="30" alt="GooglePlus">  </a></li>
        </ul>

    <div class="container body-content">

        
        @RenderBody()
            
            
        
        <hr />
                    
       

        <footer>
            <p>&copy; @DateTime.Now.Year - AnkeTeam Application</p>
        </footer>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

WebApplication1/WebApplication1/Views/Shared/_UyeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <style type="text/css">
        /*Madde imlerini kaldırıp tüm başlıkları alt alta sıralayalım.*/
        #menum ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }
        /*Ana menü başlıklarının alt alta değil de soldan sağa doğru sıralanması için float:left; özelliğine kullanalım. Çünkü yatay menü yapıyoruz.*/
        #menum li {
            float: left;
            position: relative;
            width: 150px;
        }
            /*
            Şimdi alt menu olarak açılacak alt menümüzün ayarlamasını yapıyoruz.
            Alt menü olarak açılacak menümüzün pozisyonunu : Satır yüksekliği (line-height) + kenar boşluğu (padding) + kenar çizgi kalınlıkları

            Satır yüksekliğini sonradan 16 px vereceğiz. Alt ve üst kenar boşluklarına 2 px verelim, kenar çizgileri de 1px olsun (alt ve üst hesaba dahil olacak),
            Toplam 16+(2x2)+(2x1)=22 px olacaktır.

            Alt açılan menünün üst çizgisi ile üst menümüzün alt çizgisi üst üste geleceği için alt menümüzün açılması gereken pozisyonu, yukarıdan 22-1=21 px olarak ayarlamamız daha doğru olacaktır. Yine sayfamız ilk yüklendiğinde alt menünün gözükmemesi için “display:none;” yapılmalıdır.
            */
            #menum li ul {
                display: none; /*Alt menüleri görünmez yapar*/
                left: 0; /*Soldan boşlukları temizler*/
                position: absolute; /*Alt menünün poziyonunu üst menüye göre göreceli olarak ayarlar*/
                top: 21px; /*üstten 21px boşluk bırakır*/
            }
        /*Menümüze biraz görsellik katalım*/
        #menum ul li a {
            background: #c2d378;
            border: none;
            border-bottom-color: none;
            color: #170101;
            display: block;
            font: bold 12px Arial, Helvetica, sans-serif;
            margin: 0;
            padding: 3px 5px;
            text-decoration: none;
            line-height: 16px;
        }
            /*Menü üzerine geldiğimizde yazıların kırmızı olması ve zeminin renginin beyaz kalması için*/
            #menum ul li a:hover {
                background: #c2d378;
                color: #cfffc4;
            }
        /*Üzerine geldiğimizde Alt menülerin gözükmesi için ise*/
        #menum li:hover ul {
            display: block;
        }
    </style>







</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <h2 style="font-size:15px">
                <a><img src="~/images/anketeam.jpg" width="300" height="60" alt="Örnek Resim"></a>


            </h2>


            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>


            </div>




            <div class="navbar-collapse collapse">



                <div id="menum">

                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Anasayfa", "UyeAnaSinif", "Uyeler")</li>
                        <li>@Html.ActionLink("Anketlerim", "Anketlerim", "Uyeler")</li>
                        <li>@Html.ActionLink("Kullanım Şekli", "KullanimSekli", "Home")</li>


                        <li>
                            <a href="#">Örnekler</a>
                            <ul>
                                <li>@Html.ActionLink("Anket Örnekleri", "Ornekler", "Home")</li>
                                <li>@Html.ActionLink("Anket Şablonları", "AnketSablonlari", "Home")</li>
                                <li>@Html.ActionLink("Anket Türleri", "AnketTurleri", "Home")</li>
                                <li>@Html.ActionLink("Anket İpucları", "AnketIpuclari", "Home")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#">Anket Hizmetleri</a>
                            <ul>
                                <li>@Html.ActionLink("Çok Kullanıcılı Bir Hesap Satın Alın", "AnketHizmetleri", "Home")</li>
                                <li>@Html.ActionLink("Anket Kıstasları", "AnketKistaslari", "Home")</li>

                            </ul>
                        </li>


                        <li>@Html.ActionLink("Planlar ve Fiyatlandırma", "PlanlarveFiyatlandirma", "Home")</li>
                    </ul>
                   
                </div>
            </div>
        </div>


    </div>
    <br>   </BR>
    <br>   </BR>



    <ul class="navbar  navbar-right">
        <h1 style="font-size:20px"><a>Bizi takip <br /> edin</a> </h1>
        <li><a href="http://www.facebook.com.tr/anketeam"><img src="~/images/face.png" width="30" height="30" alt="Facebook">  </a></li>
        <li> <a href="https://twitter.com/nuranozdemir61"><img src="~/images/twitter.png" width="30" height="30" alt="Twitter">  </a></li>
        <li> <a href="https://www.linkedin.com"><img src="~/images/lin.png" width="30" height="30" alt="LinkedIn">  </a></li>
        <li> <a href="https://plus.google.com"><img src="~/images/google.jpg" width="30" height="30" alt="GooglePlus">  </a></li>
    </ul>

    <div class="container body-content">


        @RenderBody()



        <hr />



        <footer>
            <p>&copy; @DateTime.Now.Year - AnkeTeam Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>